wmmodel.settings:
    type: config_object
    label: Settings
    mapping:
        override_account_proxy:
            type: boolean
            label: 'Make AccountProxyInterface::getAccount return the user entity.'
